// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types-enhanced';

const SUPABASE_URL = "https://fdojtcfltiyjqrwyymwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkb2p0Y2ZsdGl5anFyd3l5bXdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MzY1MTMsImV4cCI6MjA2ODUxMjUxM30.OAdLyD7Dp-XzvXun-e2TkprHMLlbYGdXLJEoXbPtZoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
