// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types-enhanced';

const SUPABASE_URL = "https://yxbdqiippivbhtvvsgnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4YmRxaWlwcGl2Ymh0dnZzZ25kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5Nzk2MTMsImV4cCI6MjA1ODU1NTYxM30.4IODx6uc1xha82nwH-AJlr1PtZQOFHTdZI4t6wuBjsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);